language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3

gemfile:
  - Gemfile
  - gemfiles/activesupport-4.gemfile

matrix:
  exclude:
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile

before_install:
  - gem update bundler

before_install:
  - gem update bundler

script: bundle exec rake test
